name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev libssl-dev
    - name: Verify SQLite installation
      run: |
        dpkg -l | grep sqlite
        ls /usr/lib/x86_64-linux-gnu/libsqlite3.*
    - name: Clean build
      run: make clean
    - name: Build with verbose output
      run: make V=1
